language: node_js

node_js:
    - 11

install:
    - yarn install

cache:
    directories:
        - $HOME/.npm

before_script:
    - yarn run build:dll

script:
    - yarn run build

after_success:
    - ls ./dist
